const CARD_TYPES = Object.freeze({
    HEARTS: "HEARTS",
    SPADES: "SPADES",
    KLEAVERS: "KLEAVERS",
    DIAMONDS: "DIAMONDS"
});

export const Cards = Object.freeze({
    HEA2: { STRENGTH: 2, TYPE: CARD_TYPES.HEARTS, IMAGE: "/images/cards/hea2.png"},
    HEA3: { STRENGTH: 3, TYPE: CARD_TYPES.HEARTS, IMAGE: "/images/cards/hea3.png" },
    HEA4: { STRENGTH: 4, TYPE: CARD_TYPES.HEARTS, IMAGE: "/images/cards/hea4.png" },
    HEA5: { STRENGTH: 5, TYPE: CARD_TYPES.HEARTS, IMAGE: "/images/cards/hea5.png" },
    HEA6: { STRENGTH: 6, TYPE: CARD_TYPES.HEARTS, IMAGE: "/images/cards/hea6.png" },
    HEA7: { STRENGTH: 7, TYPE: CARD_TYPES.HEARTS, IMAGE: "/images/cards/hea7.png" },
    HEA8: { STRENGTH: 8, TYPE: CARD_TYPES.HEARTS, IMAGE: "/images/cards/hea8.png" },
    HEA9: { STRENGTH: 9, TYPE: CARD_TYPES.HEARTS, IMAGE: "/images/cards/hea9.png" },
    HEA10: { STRENGTH: 10, TYPE: CARD_TYPES.HEARTS, IMAGE: "/images/cards/hea10.png" },
    HEAJ: { STRENGTH: 11, TYPE: CARD_TYPES.HEARTS, IMAGE: "/images/cards/heaJ.png" },
    HEAQ: { STRENGTH: 12, TYPE: CARD_TYPES.HEARTS, IMAGE: "/images/cards/heaQ.png" },
    HEAK: { STRENGTH: 13, TYPE: CARD_TYPES.HEARTS, IMAGE: "/images/cards/heaK.png" },
    HEAA: { STRENGTH: 14, TYPE: CARD_TYPES.HEARTS, IMAGE: "/images/cards/heaA.png" },

    DIA2: { STRENGTH: 2, TYPE: CARD_TYPES.DIAMONDS, IMAGE: "/images/cards/dia2.png" },
    DIA3: { STRENGTH: 3, TYPE: CARD_TYPES.DIAMONDS, IMAGE: "/images/cards/dia3.png" },
    DIA4: { STRENGTH: 4, TYPE: CARD_TYPES.DIAMONDS, IMAGE: "/images/cards/dia4.png" },
    DIA5: { STRENGTH: 5, TYPE: CARD_TYPES.DIAMONDS, IMAGE: "/images/cards/dia5.png" },
    DIA6: { STRENGTH: 6, TYPE: CARD_TYPES.DIAMONDS, IMAGE: "/images/cards/dia6.png" },
    DIA7: { STRENGTH: 7, TYPE: CARD_TYPES.DIAMONDS, IMAGE: "/images/cards/dia7.png" },
    DIA8: { STRENGTH: 8, TYPE: CARD_TYPES.DIAMONDS, IMAGE: "/images/cards/dia8.png" },
    DIA9: { STRENGTH: 9, TYPE: CARD_TYPES.DIAMONDS, IMAGE: "/images/cards/dia9.png" },
    DIA10: { STRENGTH: 10, TYPE: CARD_TYPES.DIAMONDS, IMAGE: "/images/cards/dia10.png" },
    DIAJ: { STRENGTH: 11, TYPE: CARD_TYPES.DIAMONDS, IMAGE: "/images/cards/diaJ.png" },
    DIAQ: { STRENGTH: 12, TYPE: CARD_TYPES.DIAMONDS, IMAGE: "/images/cards/diaQ.png" },
    DIAK: { STRENGTH: 13, TYPE: CARD_TYPES.DIAMONDS, IMAGE: "/images/cards/diaK.png" },
    DIAA: { STRENGTH: 14, TYPE: CARD_TYPES.DIAMONDS, IMAGE: "/images/cards/diaA.png" },

    SPA2: { STRENGTH: 2, TYPE: CARD_TYPES.SPADES, IMAGE: "/images/cards/spa2.png" },
    SPA3: { STRENGTH: 3, TYPE: CARD_TYPES.SPADES, IMAGE: "/images/cards/spa3.png" },
    SPA4: { STRENGTH: 4, TYPE: CARD_TYPES.SPADES, IMAGE: "/images/cards/spa4.png" },
    SPA5: { STRENGTH: 5, TYPE: CARD_TYPES.SPADES, IMAGE: "/images/cards/spa5.png" },
    SPA6: { STRENGTH: 6, TYPE: CARD_TYPES.SPADES, IMAGE: "/images/cards/spa6.png" },
    SPA7: { STRENGTH: 7, TYPE: CARD_TYPES.SPADES, IMAGE: "/images/cards/spa7.png" },
    SPA8: { STRENGTH: 8, TYPE: CARD_TYPES.SPADES, IMAGE: "/images/cards/spa8.png" },
    SPA9: { STRENGTH: 9, TYPE: CARD_TYPES.SPADES, IMAGE: "/images/cards/spa9.png" },
    SPA10: { STRENGTH: 10, TYPE: CARD_TYPES.SPADES, IMAGE: "/images/cards/spa10.png" },
    SPAJ: { STRENGTH: 11, TYPE: CARD_TYPES.SPADES, IMAGE: "/images/cards/spaJ.png" },
    SPAQ: { STRENGTH: 12, TYPE: CARD_TYPES.SPADES, IMAGE: "/images/cards/spaQ.png" },
    SPAK: { STRENGTH: 13, TYPE: CARD_TYPES.SPADES, IMAGE: "/images/cards/spaK.png" },
    SPAA: { STRENGTH: 14, TYPE: CARD_TYPES.SPADES, IMAGE: "/images/cards/spaA.png" },

    KLE2: { STRENGTH: 2, TYPE: CARD_TYPES.KLEAVERS, IMAGE: "/images/cards/kle2.png" },
    KLE3: { STRENGTH: 3, TYPE: CARD_TYPES.KLEAVERS, IMAGE: "/images/cards/kle3.png" },
    KLE4: { STRENGTH: 4, TYPE: CARD_TYPES.KLEAVERS, IMAGE: "/images/cards/kle4.png" },
    KLE5: { STRENGTH: 5, TYPE: CARD_TYPES.KLEAVERS, IMAGE: "/images/cards/kle5.png" },
    KLE6: { STRENGTH: 6, TYPE: CARD_TYPES.KLEAVERS, IMAGE: "/images/cards/kle6.png" },
    KLE7: { STRENGTH: 7, TYPE: CARD_TYPES.KLEAVERS, IMAGE: "/images/cards/kle7.png" },
    KLE8: { STRENGTH: 8, TYPE: CARD_TYPES.KLEAVERS, IMAGE: "/images/cards/kle8.png" },
    KLE9: { STRENGTH: 9, TYPE: CARD_TYPES.KLEAVERS, IMAGE: "/images/cards/kle9.png" },
    KLE10: { STRENGTH: 10, TYPE: CARD_TYPES.KLEAVERS, IMAGE: "/images/cards/kle10.png" },
    KLEJ: { STRENGTH: 11, TYPE: CARD_TYPES.KLEAVERS, IMAGE: "/images/cards/kleJ.png" },
    KLEQ: { STRENGTH: 12, TYPE: CARD_TYPES.KLEAVERS, IMAGE: "/images/cards/kleQ.png" },
    KLEK: { STRENGTH: 13, TYPE: CARD_TYPES.KLEAVERS, IMAGE: "/images/cards/kleK.png" },
    KLEA: { STRENGTH: 14, TYPE: CARD_TYPES.KLEAVERS, IMAGE: "/images/cards/kleA.png" },
});